### PR TITLE
[android] Update to latest Taichi API

### PR DESCRIPTION
**Pull request by ghuau-innopeak**
This include the fixes for Vulkan Semaphore for example.

### CODE REVIEW

**Comment by ailzhang** [comment]
@PENGUINLIONG would you mind help review this PR? (maybe also make sure it still runs :P Thanks a lot!

**Comment by PENGUINLIONG** [comment]
Thanks for your contribution! I wonder if there is a Taichi version requirement after this change? It seems targeting neither v1.0.0 nor v1.0.1

**Comment by PENGUINLIONG** [comment]
BTW it would be great if the updated building process could be documented [`here`](https://github.com/taichi-dev/taichi-aot-demo/blob/master/implicit_fem/README.md). :)

**Comment by PENGUINLIONG** [comment]
I have tried the lastest master and it seems working, while the motion is significantly slower than the previous version. Is this an expected behavior?

**Comment by ghuau-innopeak** [comment]
@PENGUINLIONG Good call for the slowness, I pushed an update, I was using the LINEAR_ACCELERATION instead of the ACCELEROMETER..., that should be fixed :)
For the README, I updated the path to the build library but I believe the current README should work no?

Good question about the targeted version, it should work with anything higher v1.0.1, how should we handle this? Can we check the version when loading the AOT module against the C++ code?

**Comment by ghuau-innopeak** [comment]
@PENGUINLIONG Were you able to confirm the FPS drop from Java to C++? I ran some tests on my side and I didn't see any change in the FPS.

**Review by ailzhang — APPROVED** [review]
@PENGUINLIONG confirmed that FPS issue is no longer there. Thanks a ton!

**Comment by Jingzheng-Li** [comment]
Hi, I am pretty inexperienced at this, and have encountered some problems while compiling implicit FEM,

$ make
make: *** No targets specified and no makefile found.  Stop.

The files generated by cmake are

$ ls
ALL_BUILD.vcxproj          ZERO_CHECK.vcxproj.filters
ALL_BUILD.vcxproj.filters  cmake_install.cmake
CMakeCache.txt             implicit_fem.sln
CMakeFiles/                implicit_fem.vcxproj
ZERO_CHECK.vcxproj         implicit_fem.vcxproj.filters

My system environment is win10/vs2019, how can I solve this problem? Thank you so much!

**Comment by PENGUINLIONG** [comment]
could you try cmake --build .

**Pull request merged**
